---
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    pkg:
      - git
      - python3
      - python3-pip
      - python3-venv
    state: present
- name: Create series folder
  become: true
  ansible.builtin.file:
    path: /home/sonarr/series
    state: directory
    owner: sonarr
    group: sonarr
    mode: 0775
- name: Create movies folder
  become: true
  ansible.builtin.file:
    path: /home/radarr/movies
    state: directory
    owner: radarr
    group: radarr
    mode: 0775
- name: Create media group
  ansible.builtin.group:
    name: media
    state: present
- name: Add sonarr user to media group
  ansible.builtin.user:
    name: sonarr
    groups: media
    append: true
- name: Add radarr user to media group
  ansible.builtin.user:
    name: radarr
    groups: media
    append: true
- name: Add qbittorrent user to media group
  ansible.builtin.user:
    name: qbittorrent
    groups: media
    append: true
- name: Create completed downloads folder
  become: true
  ansible.builtin.file:
    path: /home/qbittorrent/downloads/completed
    state: directory
    owner: qbittorrent
    group: media
    mode: 0775
- name: Create pending downloads folder
  become: true
  ansible.builtin.file:
    path: /home/qbittorrent/downloads/pending
    state: directory
    owner: qbittorrent
    group: media
    mode: 0775
- name: Clone latest Flemmar version
  ansible.builtin.git:
    repo: https://github.com/Flemmarr/Flemmarr.git
    dest: /tmp/flemmar
- name: Install packages
  ansible.builtin.pip:
    chdir: /tmp/flemmar/src
    requirements: requirements.txt
    virtualenv: /tmp/flemmar/.venv
    virtualenv_command: python3 -m venv
- name: Get Sonarr API key
  ansible.builtin.shell:
    cmd: "curl -s http://localhost:8989/sonarr/initialize.js | sed -nr \"s/\\s*apiKey: '(\\S+)',/\\1/p\""
  register: sonarr_api_key
- name: Get Radarr API key
  ansible.builtin.shell:
    cmd: "curl -s http://localhost:7878/radarr/initialize.js | sed -nr \"s/\\s*apiKey: '(\\S+)',/\\1/p\""
  register: radarr_api_key
- name: Create config folder
  ansible.builtin.file:
    path: /tmp/flemmar/src/config
    state: directory
    mode: 0644
- name: Copy the Flemmar configuration file to the host
  ansible.builtin.template:
    src: templates/flemmarr.yml.j2
    dest: /tmp/flemmar/src/config/config.yml
    mode: 0644
- name: Run Flemmar
  ansible.builtin.shell:
    chdir: /tmp/flemmar/src
    cmd: /tmp/flemmar/.venv/bin/python run.py
  notify:
    - Restart the Sonarr service
    - Restart the Radarr service
    - Restart the Prowlarr service
