---
- name: Create repository configuration folder
  ansible.builtin.file:
    path: /usr/local/etc/pkg/repos
    state: directory
- name: Copy base repository configuration
  ansible.builtin.copy:
    src: /etc/pkg/FreeBSD.conf
    dest: /usr/local/etc/pkg/repos/FreeBSD.conf
    remote_src: true
- name: Change repository branch from 'quarterly' to 'latest'
  ansible.builtin.replace:
    path: /usr/local/etc/pkg/repos/FreeBSD.conf
    after: '  url: "pkg\+http:\/\/pkg\.FreeBSD\.org\/\$\{ABI\}\/'
    before: '",'
    regexp: quarterly
    replace: latest
- name: Update repository cache
  ansible.builtin.shell:
    cmd: pkg update
- name: Upgrade packages
  ansible.builtin.shell:
    cmd: pkg upgrade -y
