---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - git
      - python3
    state: present
- name: Clone latest Flemmar version
  ansible.builtin.git:
    repo: https://github.com/Flemmarr/Flemmarr.git
    dest: /tmp/flemmar
    version: master
- name: Install packages
  ansible.builtin.pip:
    chdir: /tmp/flemmar/src
    requirements: requirements.txt
    virtualenv: /tmp/flemmar/.venv
    virtualenv_command: python3 -m venv
- name: Get Sonarr API key
  ansible.builtin.shell:
    cmd: "curl -s http://localhost:8989/initialize.js | sed -n -r -E \"s/^.*apiKey:.*'(.*)',/\\1/p\""
  register: sonarr_api_key
- name: Get Radarr API key
  ansible.builtin.shell:
    cmd: "curl -s http://localhost:7878/initialize.js | sed -n -r -E \"s/^.*apiKey:.*'(.*)',/\\1/p\""
  register: radarr_api_key
- name: Create config folder
  ansible.builtin.file:
    path: /tmp/flemmar/src/config
    state: directory
    mode: 0644
- name: Copy the Flemmar configuration file to the host
  ansible.builtin.template:
    src: templates/flemmarr.yml.j2
    dest: /tmp/flemmar/src/config/config.yml
    mode: 0644
- name: Run Flemmar
  ansible.builtin.shell:
    chdir: /tmp/flemmar/src
    cmd: /tmp/flemmar/.venv/bin/python run.py
- name: Remove Flemmar after execution
  file:
    state: absent
    path: /tmp/flemmar
