---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - git
      - node16
      - yarn-node16
      - python3
      - gmake
    state: present
- name: Create Overseerr group
  ansible.builtin.group:
    name: overseerr
- name: Create Overseerr user
  ansible.builtin.user:
    name: overseerr
    group: overseerr
    comment: Overseerr
- name: Clone latest Overseerr version
  ansible.builtin.git:
    repo: https://github.com/sct/overseerr.git
    dest: /usr/local/overseerr
    version: master
- name: Install Overseerr dependencies
  ansible.builtin.shell:
    cmd: env CYPRESS_INSTALL_BINARY=0 yarn install --frozen-lockfile --network-timeout 1000000
    chdir: /usr/local/overseerr
- name: Build Overseerr
  ansible.builtin.shell:
    cmd: yarn build
    chdir: /usr/local/overseerr
- name: Change Overseerr directory owner
  ansible.builtin.file:
    path: /usr/local/overseerr
    state: directory
    owner: overseerr
    group: overseerr
    recurse: true
