---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - git
      - node16
      - yarn-node16
      - python3
      - gmake
    state: present
- name: Create Overseerr group
  ansible.builtin.group:
    name: overseerr
- name: Create Overseerr user
  ansible.builtin.user:
    name: overseerr
    group: overseerr
    comment: Overseerr
- name: Clone latest Overseerr version
  ansible.builtin.git:
    repo: https://github.com/sct/overseerr.git
    dest: /usr/local/share/overseerr
    version: master
- name: Install Overseerr dependencies
  ansible.builtin.shell:
    cmd: CYPRESS_INSTALL_BINARY=0 yarn install --frozen-lockfile --network-timeout 1000000
    chdir: /usr/local/share/overseerr
- name: Build Overseerr
  ansible.builtin.shell:
    cmd: yarn build
    chdir: /usr/local/share/overseerr
- name: Remove development dependencies
  ansible.builtin.shell:
    cmd: yarn install --production --ignore-scripts --prefer-offline
    chdir: /usr/local/share/overseerr
