---
# tasks file for media_server
- name: Update and upgrade APT
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes
# - name: Import Nginx tasks
#   ansible.builtin.import_tasks: nginx.yml
# - name: Import qBittorrent tasks
#   ansible.builtin.import_tasks: qbittorrent.yml
# - name: Import Prowlarr tasks
#   ansible.builtin.import_tasks: prowlarr.yml
# - name: Import Sonarr tasks
#   ansible.builtin.import_tasks: sonarr.yml
# - name: Import Radarr tasks
#   ansible.builtin.import_tasks: radarr.yml
# - name: Import Jellyfin tasks
#   ansible.builtin.import_tasks: jellyfin.yml
- name: Import Flemmar tasks
  ansible.builtin.import_tasks: flemmarr.yml
